apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: goormthon-5

resources:
- backend.yaml
- ingress.yaml

configMapGenerator:
- name: backend-config
  files:
  - config/.env

commonLabels:
  app: backend
  team: goormthon-5
