apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: goormthon-5

resources:
- secret.yaml
- service.yaml
- statefulset.yaml

configMapGenerator:
- name: postgres-config
  files:
  - postgresql.conf
  - pg_hba.conf

- name: postgres-init
  files:
  - init.sql

commonLabels:
  app: postgres
  component: database
  team: goormthon-5
